// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Twitch_chat_bot.Core;

namespace Twitch_chat_bot.Migrations
{
    [DbContext(typeof(RouletteDbContext))]
    partial class RouletteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Twitch_chat_bot.Core.TwitchUser", b =>
                {
                    b.Property<string>("TwitchId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Balance");

                    b.Property<bool>("CanPlay");

                    b.HasKey("TwitchId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
